### PR TITLE
Forward port to master of the #93 fix

### PR DESCRIPTION
**Pull request by cazino**
The fix for #93 was made in 0.3. The bug also affects master so we should forward port the fix to master.
I branched 0.3-merge-in-master from master, and manually merged  0.3 in it.

### CODE REVIEW

**Comment by NicolasT** [comment]
Jenkins, add to whitelist, and ok to test.

**Comment by NicolasT** [comment]
Doesn't seem to work as-is due to failing imports. Did you have some `.pyc` files without corresponding `.py` sources left in your tree when running `tox` locally? Try `git clean -dxf` (run `git status --ignored` first!) to cleanup.

**Comment by cazino** [comment]
My mistake during the merge, I kept the the wrong exception import in http_utils.py
InvariantViolation exception is defined in scality_sproxyd_client.exceptions now.
Tests should pass.

**Comment by NicolasT** [comment]
Could you squash the fixup commit into the merge, so we don't have any non-working commits at all?

**Comment by cazino** [comment]
Done.

**Comment by NicolasT** [comment]
LGTM

**Pull request merged**
