### PR TITLE
Jenkins: Add `swift-master` job

### PR DESCRIPTION
**Pull request by NicolasT**

### CODE REVIEW

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/31/
Test failed.

**Comment by NicolasT** [comment]
Jenkins, retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/32/<h2>Build result: ABORTED</span></h2>[...truncated 10 lines...] > git rev-parse remotes/origin/pr/42/merge^{commit} # timeout=10Checking out Revision 525491e4484b33aea674f4a880e91c4d88dcd017 (origin/pr/42/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 525491e4484b33aea674f4a880e91c4d88dcd017First time build. Skipping changelog.Triggering swift-tox » ubuntu1404,py27-swift1.13.1Triggering swift-tox » ubuntu1404,py27-swift2.2.0Triggering swift-tox » ubuntu1404,py27-swiftheadTriggering swift-tox » ubuntu1404,pep8Configuration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: All nodes of label ‘ubuntu1404’ are offlineConfiguration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: Waiting for next available executorConfiguration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: ubuntu1404-953 is offlineConfiguration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: Waiting for next available executor on ubuntu1404-953swift-tox » ubuntu1404,py27-swift1.13.1 appears to be cancelledswift-tox » ubuntu1404,py27-swift1.13.1 completed with result ABORTEDConfiguration swift-tox » ubuntu1404,py27-swift2.2.0 is still in the queue: Waiting for next available executor on ubuntu1404-953swift-tox » ubuntu1404,py27-swift2.2.0 appears to be cancelledswift-tox » ubuntu1404,py27-swift2.2.0 completed with result ABORTEDConfiguration swift-tox » ubuntu1404,py27-swifthead is still in the queue: Waiting for next available executor on ubuntu1404-953swift-tox » ubuntu1404,py27-swifthead appears to be cancelledswift-tox » ubuntu1404,py27-swifthead completed with result ABORTEDConfiguration swift-tox » ubuntu1404,pep8 is still in the queue: Waiting for next available executor on ubuntu1404-953swift-tox » ubuntu1404,pep8 appears to be cancelledswift-tox » ubuntu1404,pep8 completed with result ABORTED
Test failed.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/33/<h2>Build result: FAILURE</span></h2>[...truncated 5 lines...]Fetching upstream changes from https://github.com/scality/ScalitySproxydSwift.git > git --version # timeout=10 > git -c core.askpass=true fetch --tags --progress https://github.com/scality/ScalitySproxydSwift.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* > git rev-parse origin/pr/42/merge^{commit} # timeout=10 > git branch -a --contains 9ae1a2a0460725dc2ce665fe7b20a3d9b1e2e064 # timeout=10 > git rev-parse remotes/origin/pr/42/merge^{commit} # timeout=10Checking out Revision 9ae1a2a0460725dc2ce665fe7b20a3d9b1e2e064 (origin/pr/42/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 9ae1a2a0460725dc2ce665fe7b20a3d9b1e2e064 > git rev-list 525491e4484b33aea674f4a880e91c4d88dcd017 # timeout=10First time build. Skipping changelog.Triggering swift-tox » ubuntu1404,py27-swift1.13.1Triggering swift-tox » ubuntu1404,py27-swift2.2.0Triggering swift-tox » ubuntu1404,py27-swiftheadTriggering swift-tox » ubuntu1404,pep8Configuration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: All nodes of label ‘ubuntu1404’ are offlineConfiguration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: ubuntu1404-f0a is offlineConfiguration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: Waiting for next available executorConfiguration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: ubuntu1404-953 is offlineConfiguration swift-tox » ubuntu1404,py27-swift1.13.1 is still in the queue: Waiting for next available executor on ubuntu1404-953swift-tox » ubuntu1404,py27-swift1.13.1 completed with result FAILUREswift-tox » ubuntu1404,py27-swift2.2.0 completed with result FAILUREswift-tox » ubuntu1404,py27-swifthead completed with result FAILUREswift-tox » ubuntu1404,pep8 completed with result FAILURE
Test failed.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/35/<h2>Build result: FAILURE</span></h2>GitHub pull request #42 of commit 10e75590d80304d37e3b1ca07456b09cf88754ea automatically merged.Building on master in workspace /var/lib/jenkins/workspace/swift-tox > git rev-parse --is-inside-work-tree # timeout=10Fetching changes from the remote Git repository > git config remote.origin.url https://github.com/scality/ScalitySproxydSwift.git # timeout=10Fetching upstream changes from https://github.com/scality/ScalitySproxydSwift.git > git --version # timeout=10 > git -c core.askpass=true fetch --tags --progress https://github.com/scality/ScalitySproxydSwift.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* > git rev-parse origin/pr/42/merge^{commit} # timeout=10 > git branch -a --contains 0db7f93c9a6d971af73a20fba93d0d651062bcd6 # timeout=10 > git rev-parse remotes/origin/pr/42/merge^{commit} # timeout=10Checking out Revision 0db7f93c9a6d971af73a20fba93d0d651062bcd6 (origin/pr/42/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 0db7f93c9a6d971af73a20fba93d0d651062bcd6 > git rev-list 9ae1a2a0460725dc2ce665fe7b20a3d9b1e2e064 # timeout=10Triggering swift-tox » ubuntu1404,py27-swift1.13.1Triggering swift-tox » ubuntu1404,py27-swift2.2.0Triggering swift-tox » ubuntu1404,py27-swiftheadTriggering swift-tox » ubuntu1404,pep8swift-tox » ubuntu1404,py27-swift1.13.1 completed with result FAILUREswift-tox » ubuntu1404,py27-swift2.2.0 completed with result SUCCESSswift-tox » ubuntu1404,py27-swifthead completed with result SUCCESSswift-tox » ubuntu1404,pep8 completed with result FAILURE
Test failed.

**Comment by NicolasT** [comment]
Jenkins, retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/36/
Test passed.

**Pull request merged**
