### PR TITLE
Fix pep8: "do not assign a lambda expression, use a def"

### PR DESCRIPTION
**Pull request by JordanP**
So be it.

### CODE REVIEW

**Comment by NicolasT** [comment]
Meh :-P

**Comment by JordanP** [comment]
Is that a +1 :) ?

**Comment by NicolasT** [comment]
It's `So be it` with a slight silent `(grrr stupid rule)` coming with it.

**Comment by JordanP** [comment]
Yeah, this rule is new. Because the failure is new. Anyway, easier to fix than to add another exception.

**Comment by NicolasT** [comment]
Could generalize as well:

```python
def map_maybe(f, v):
    return f(v) if v is not None else None

class ...:
    def ...:
        self._conn_timeout = map_maybe(float, conf.get('sproxyd_conn_timeout'))
        self._read_timeout = map_maybe(float, conf.get('sproxyd_proxy_timeout'))
```
:grin:

**Comment by JordanP** [comment]
Call me maybe :musical_note:

**Pull request merged**
