### PR TITLE
Test: Fix `splice_utils` test when `/proc/sys/fs/pipe-max-size` is missing

### PR DESCRIPTION
**Pull request by NicolasT**
On older systems (RHEL6), this procfs entry is missing. Whilst the code in `splice_utils` handles this gracefully, the tests fail.

This commit adjusts the test code to handle this case correctly.

### CODE REVIEW

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/swift-tox/144/<h2>Build result: FAILURE</span></h2>[...truncated 21 lines...]Triggering swift-tox » py27-swift2.2.0,ubuntu12-largeTriggering swift-tox » py27-swifthead,centos7-largeTriggering swift-tox » py27-swift2.2.0,centos7-largeTriggering swift-tox » py27-swift1.13.1,ubuntu12-largeTriggering swift-tox » py26-swift1.13.1,centos6-largeTriggering swift-tox » py26-swifthead,centos6-largeTriggering swift-tox » pep8,ubuntu14-largeConfiguration swift-tox » py27-swifthead,ubuntu12-large is still in the queue: Waiting for next available executor on ubuntu12-largeConfiguration swift-tox » py27-swifthead,ubuntu12-large is still in the queue: All nodes of label ‘ubuntu12-large’ are offlineConfiguration swift-tox » py27-swifthead,ubuntu12-large is still in the queue: Waiting for next available executor on ubuntu12-largeswift-tox » py27-swifthead,ubuntu12-large completed with result FAILUREswift-tox » py27-swift2.2.0,ubuntu14-large completed with result SUCCESSswift-tox » py26-swift2.2.0,centos6-large completed with result UNSTABLEswift-tox » py27-swift1.13.1,centos7-large completed with result SUCCESSswift-tox » py27-swifthead,ubuntu14-large completed with result SUCCESSswift-tox » py27-swift1.13.1,ubuntu14-large completed with result SUCCESSswift-tox » py27-swift2.2.0,ubuntu12-large completed with result SUCCESSswift-tox » py27-swifthead,centos7-large completed with result SUCCESSswift-tox » py27-swift2.2.0,centos7-large completed with result SUCCESSswift-tox » py27-swift1.13.1,ubuntu12-large completed with result SUCCESSswift-tox » py26-swift1.13.1,centos6-large completed with result SUCCESSswift-tox » py26-swifthead,centos6-large completed with result UNSTABLEswift-tox » pep8,ubuntu14-large completed with result SUCCESSSetting status of fa8fcac43fc243e6ec93914b6da585f8c3373f2a to FAILURE with url https://37.187.159.67:5443/job/swift-tox/144/ and message: Merged build finished.
Test FAILed.

**Comment by NicolasT** [comment]
Fixing the test brought up another issue (`fcntl` command `F_GETPIPE_SZ` not supported). Will need to work-around that one as well before this can be merged.

I'm afraid this means the package with Swift >= 2.0 and `splice` enabled on a CentOS6 will break.

**Comment by NicolasT** [comment]
Maybe this should go into 0.3 instead (if #81 is confirmed).

**Comment by NicolasT** [comment]
Superseded by #82.

**Pull request closed without merging**
