### PR TITLE
Jenkins: Add job scripts

### PR DESCRIPTION
**Pull request by NicolasT**

### CODE REVIEW

**Comment by NicolasT** [comment]
This is mainly a test for the Jenkins - GitHub integration.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/13/
Test passed.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/14/
Test passed.

**Comment by NicolasT** [comment]
Retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/15/
Test failed.

**Comment by NicolasT** [comment]
Dependency installation issue in build 15. Rebuild this please.

**Comment by NicolasT** [comment]
Dependency installation failed in build 15. Retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/16/
Test passed.

**Pull request merged**
