### PR TITLE
Jenkins: Save xUnit results

### PR DESCRIPTION
**Pull request by NicolasT**

### CODE REVIEW

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/26/<h2>Build result: FAILURE</span></h2>[...truncated 3 lines...]Fetching changes from the remote Git repository > git config remote.origin.url https://github.com/scality/ScalitySproxydSwift.git # timeout=10Fetching upstream changes from https://github.com/scality/ScalitySproxydSwift.git > git --version # timeout=10 > git -c core.askpass=true fetch --tags --progress https://github.com/scality/ScalitySproxydSwift.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* > git rev-parse origin/pr/41/merge^{commit} # timeout=10 > git branch -a --contains feb3dc9bbf6a8c3a1c7284a600d707d2940fcf61 # timeout=10 > git rev-parse remotes/origin/pr/41/merge^{commit} # timeout=10Checking out Revision feb3dc9bbf6a8c3a1c7284a600d707d2940fcf61 (origin/pr/41/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f feb3dc9bbf6a8c3a1c7284a600d707d2940fcf61First time build. Skipping changelog.Triggering swift-tox » ubuntu1404,py27-swift2.2.0Triggering swift-tox » ubuntu1404,pep8Triggering swift-tox » ubuntu1404,py27-swiftheadTriggering swift-tox » ubuntu1404,py27-swift1.13.1Configuration swift-tox » ubuntu1404,py27-swift2.2.0 is still in the queue: ubuntu1404-large-194 is offlineConfiguration swift-tox » ubuntu1404,py27-swift2.2.0 is still in the queue: Waiting for next available executorConfiguration swift-tox » ubuntu1404,py27-swift2.2.0 is still in the queue: ubuntu1404-3f is offlineConfiguration swift-tox » ubuntu1404,py27-swift2.2.0 is still in the queue: Waiting for next available executor on ubuntu1404-3fswift-tox » ubuntu1404,py27-swift2.2.0 completed with result SUCCESSswift-tox » ubuntu1404,pep8 completed with result FAILUREswift-tox » ubuntu1404,py27-swifthead completed with result SUCCESSswift-tox » ubuntu1404,py27-swift1.13.1 completed with result SUCCESS
Test FAILed.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/27/<h2>Build result: FAILURE</span></h2>GitHub pull request #41 of commit 34f1f8cb1ad57df2cff9cde3c8a4d82ae7ef1b4f automatically merged.Building on master in workspace /var/lib/jenkins/workspace/swift-tox > git rev-parse --is-inside-work-tree # timeout=10Fetching changes from the remote Git repository > git config remote.origin.url https://github.com/scality/ScalitySproxydSwift.git # timeout=10Fetching upstream changes from https://github.com/scality/ScalitySproxydSwift.git > git --version # timeout=10 > git -c core.askpass=true fetch --tags --progress https://github.com/scality/ScalitySproxydSwift.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* > git rev-parse origin/pr/41/merge^{commit} # timeout=10 > git branch -a --contains 454e3ef91a765d729b15cf6fc9c4b71c92a3ee56 # timeout=10 > git rev-parse remotes/origin/pr/41/merge^{commit} # timeout=10Checking out Revision 454e3ef91a765d729b15cf6fc9c4b71c92a3ee56 (origin/pr/41/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 454e3ef91a765d729b15cf6fc9c4b71c92a3ee56First time build. Skipping changelog.Triggering swift-tox » ubuntu1404,py27-swift2.2.0Triggering swift-tox » ubuntu1404,pep8Triggering swift-tox » ubuntu1404,py27-swiftheadTriggering swift-tox » ubuntu1404,py27-swift1.13.1swift-tox » ubuntu1404,py27-swift2.2.0 completed with result SUCCESSswift-tox » ubuntu1404,pep8 completed with result FAILUREswift-tox » ubuntu1404,py27-swifthead completed with result SUCCESSswift-tox » ubuntu1404,py27-swift1.13.1 completed with result SUCCESS
Test FAILed.

**Comment by NicolasT** [comment]
Jenkins, retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/28/<h2>Build result: FAILURE</span></h2>GitHub pull request #41 of commit 34f1f8cb1ad57df2cff9cde3c8a4d82ae7ef1b4f automatically merged.Building on master in workspace /var/lib/jenkins/workspace/swift-tox > git rev-parse --is-inside-work-tree # timeout=10Fetching changes from the remote Git repository > git config remote.origin.url https://github.com/scality/ScalitySproxydSwift.git # timeout=10Fetching upstream changes from https://github.com/scality/ScalitySproxydSwift.git > git --version # timeout=10 > git -c core.askpass=true fetch --tags --progress https://github.com/scality/ScalitySproxydSwift.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* > git rev-parse origin/pr/41/merge^{commit} # timeout=10 > git branch -a --contains 454e3ef91a765d729b15cf6fc9c4b71c92a3ee56 # timeout=10 > git rev-parse remotes/origin/pr/41/merge^{commit} # timeout=10Checking out Revision 454e3ef91a765d729b15cf6fc9c4b71c92a3ee56 (origin/pr/41/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 454e3ef91a765d729b15cf6fc9c4b71c92a3ee56First time build. Skipping changelog.Triggering swift-tox » ubuntu1404,py27-swift2.2.0Triggering swift-tox » ubuntu1404,pep8Triggering swift-tox » ubuntu1404,py27-swiftheadTriggering swift-tox » ubuntu1404,py27-swift1.13.1swift-tox » ubuntu1404,py27-swift2.2.0 completed with result SUCCESSswift-tox » ubuntu1404,pep8 completed with result FAILUREswift-tox » ubuntu1404,py27-swifthead completed with result SUCCESSswift-tox » ubuntu1404,py27-swift1.13.1 completed with result SUCCESS
Test FAILed.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:7443//job/swift-tox/29/
Test PASSed.

**Pull request merged**
