### PR TITLE
Fix RHEL6 'max pipe size'

### PR DESCRIPTION
**Pull request by NicolasT**
See #80, #81.

### CODE REVIEW

**Comment by NicolasT** [comment]
Right... CI fails because CentOS is not supported by the CI scripts in the 0.3 branch. Running the tests manually on a CentOS6 system works though.

**Comment by NicolasT** [comment]
```
$ git branch
* fix-centos6-max-pipe-size-0.3
  master
$ uname -a
Linux nicolas 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ git status
# On branch fix-centos6-max-pipe-size-0.3
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	env/
nothing added to commit but untracked files present (use "git add" to track)
```

```
$ tox -e py26-swift1.13.1,py26-swift2.1.0,py26-swift2.2.0,py26-swifthead
...
  py26-swift1.13.1: commands succeeded
  py26-swift2.1.0: commands succeeded
  py26-swift2.2.0: commands succeeded
  py26-swifthead: commands succeeded
  congratulations :)
```

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/swift-tox/146/<h2>Build result: FAILURE</span></h2>[...truncated 30 lines...]Triggering swift-tox » py26-swift1.13.1,centos6-largeTriggering swift-tox » py26-swifthead,centos6-largeTriggering swift-tox » pep8,ubuntu14-largeConfiguration swift-tox » py27-swifthead,ubuntu12-large is still in the queue: Waiting for next available executor on ubuntu12-largeConfiguration swift-tox » py27-swifthead,ubuntu12-large is still in the queue: All nodes of label ‘ubuntu12-large’ are offlineConfiguration swift-tox » py27-swifthead,ubuntu12-large is still in the queue: Waiting for next available executor on ubuntu12-largeswift-tox » py27-swifthead,ubuntu12-large completed with result SUCCESSswift-tox » py27-swift2.2.0,ubuntu14-large completed with result SUCCESSswift-tox » py26-swift2.2.0,centos6-large completed with result FAILUREswift-tox » py27-swift1.13.1,centos7-large completed with result FAILUREswift-tox » py27-swifthead,ubuntu14-large completed with result SUCCESSswift-tox » py27-swift1.13.1,ubuntu14-large completed with result SUCCESSswift-tox » py27-swift2.2.0,ubuntu12-large completed with result SUCCESSswift-tox » py27-swifthead,centos7-large completed with result FAILUREswift-tox » py27-swift2.2.0,centos7-large completed with result FAILUREswift-tox » py27-swift1.13.1,ubuntu12-large completed with result FAILUREswift-tox » py26-swift1.13.1,centos6-large completed with result FAILUREConfiguration swift-tox » py26-swifthead,centos6-large is still in the queue: All nodes of label ‘centos6-large’ are offlineConfiguration swift-tox » py26-swifthead,centos6-large is still in the queue: centos6-large-f45 is offlineConfiguration swift-tox » py26-swifthead,centos6-large is still in the queue: All nodes of label ‘centos6-large’ are offlineConfiguration swift-tox » py26-swifthead,centos6-large is still in the queue: centos6-large-b31 is offlineswift-tox » py26-swifthead,centos6-large completed with result FAILUREswift-tox » pep8,ubuntu14-large completed with result SUCCESSSetting status of 9f986b2d4e348a130e299fcb4efe27fb0d5a77c9 to FAILURE with url https://37.187.159.67:5443/job/swift-tox/146/ and message: Merged build finished.
Test FAILed.

**Comment by JordanP** [comment]
LGTM

**Pull request merged**
