### PR TITLE
Include the tempest test suite in the swift-functional-test job

### PR DESCRIPTION
**Pull request by cazino**
Here is a Ci run : https://37.187.159.67:5443/job/swift-functional-tests/157/

### CODE REVIEW

**Comment by cazino** [comment]
This PR should resolve #122

**Comment by JordanP** [comment]
For some reason, we fail the Tempest test called "test_container_synchronization". I know this test is a bit flaky, and we should skip it. Luckily it can be skipped easily by switching a boolean in Tempest conf (https://github.com/openstack/tempest/blob/master/tempest/api/object_storage/test_container_sync.py#L136). Could you do that, so we have a cleaner run ? I mean false negative are bad...

**Comment by cazino** [comment]
@JordanP : this is not the test which is failing. We fail this one : https://github.com/openstack/tempest/blob/master/tempest/api/object_storage/test_container_sync_middleware.py#L42

Do you still think we should skip that test ?

**Comment by JordanP** [comment]
@cazino, you're right. I'll check why it fails this afternoon.

**Comment by NicolasT** [comment]
Is this still blocked on something?

**Comment by cazino** [comment]
@JordanP is supposed to investigate on this one : https://github.com/openstack/tempest/blob/master/tempest/api/object_storage/test_container_sync_middleware.py#L42, wich is failing.

I could try to investigate if he has not time available for this. We might also want to merge right now, as we have other failures in the swift functional test suite anyway.

**Comment by NicolasT** [comment]
Not sure why that test would be failing (didn't look into a run), but the double `/` in the value of `X-Container-Sync-To` caught my eye...

**Comment by cazino** [comment]
The test output is here  : https://37.187.159.67:5443/job/swift-functional-tests/157/DEVSTACK_BRANCH=stable%2Fjuno,host=centos6-large/testReport/junit/tempest.api.object_storage.test_container_sync_middleware/ContainerSyncMiddlewareTest/test_container_synchronization_id_ea4645a1_d147_4976_82f7_e5a7a3065f80_slow_/

**Comment by JordanP** [comment]
I don't have the time the investigate more now. I see no reason to delay this. I am not worried about the failing test.

LGTM

**Comment by cazino** [comment]
I just squashed the commits. Will merge now.

**Pull request merged**
