### PR TITLE
Add Swift 2.3.0 'Kilo' Tox target

### PR DESCRIPTION
**Pull request by NicolasT**
See: https://github.com/scality/ScalitySproxydSwift/issues/134

### CODE REVIEW

**Comment by NicolasT** [comment]
Jenkins: retest this please.

**Comment by cazino** [comment]
Do we really want to run py26*swift-head and py26*swift-2.3.0 , since we discarded those two combinations is the functional tests ?

**Comment by NicolasT** [comment]
I would think so since it's a supported configuration (for now. Swift `master`/Liberty could become Python2.7-only).

**Comment by cazino** [comment]
Fine, then LGTM.

**Pull request merged**
