### PR TITLE
0.3 for master

### PR DESCRIPTION
**Pull request by cazino**
Forward port to master of this py26 fix.

### CODE REVIEW

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/swift-tox/185/
Test PASSed.

**Comment by JordanP** [comment]
This seems already in branch 0.3... It was merged in 0.3 during PR #88

**Comment by JordanP** [comment]
Ahh, nevermind, this PR is for master...

**Comment by NicolasT** [comment]
LGTM

**Pull request merged**
